---
    name: Call a db CI workflow

    on:
      push:
        branches:
          - '*'
        paths:
          - 'terraform/aurora/**'
          - '.github/workflows/db-ci.yaml'

    jobs:
      call_ci_workflow_for_db:
        permissions:
          id-token: write
          contents: read
          pull-requests: write
        uses: ./.github/workflows/reusable-ci-workflow.yaml
        with:
          module_path: aurora
          aws_region: us-east-1
          dev: true
          stg: false
          prod: false