---
name: Call a ecs CD workflow

on:
  push:
    branches:
      - master
    paths:
      - "terraform/ecs/**"
      - ".github/workflows/ecs-cd.yaml"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call_cd_workflow_for_ecs:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: ./.github/workflows/reusable-cd-workflow.yaml
    with:
      module_path: ecs
      aws_region: us-east-1
      dev: true
      stg: false
      prod: false
