---
name: Call a eks CI workflow

on:
  push:
    branches:
      - "*"
    paths:
      - "terraform/eks/**"
      - ".github/workflows/eks-ci.yaml"

jobs:
  call_ci_workflow_for_eks:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: ./.github/workflows/reusable-ci-workflow.yaml
    with:
      module_path: eks
      aws_region: us-east-1
      dev: true
      stg: false
      prod: false
